# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d7c3c304cc366d10ca3722d6aac8877a9e2bb68de21b134dd6a33f126fc4720b88f8e55a40aee90e9726943052b7b5aabdf9a7a084642bd90986acbaa7b2d243

test:
  secret_key_base: 07edfe242285b993197d682070b3df8ff28d6fcf4d13b82ab30eccfe4711ebf9c57917fa0385e628c3f6b0950bc349d74f22b39d668902e4e1d5e5b0e295ee30

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
